#!/bin/bash

# redirect the callgraph output to stdout and delete stderr
opt -print-callgraph $1 >callgraph 2>&1 1>/dev/null

# execute the java main.class file
java -Xms128m -Xmx128m -cp ../bin Main callgraph $2 $3 2>/dev/null 
